In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1, arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0, 1, 2], index = ['T', 'U', 'V'])
ser2 = Series([3, 4], index = ['X', 'Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3), columns = ['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns = ['Y', 'Q', 'X'])

In [13]:
dframe1

X         Y         Z
0 -0.189184  0.119048 -0.959709
1 -1.117993 -0.039461  0.286240
2  0.759573  0.736577 -0.124798
3  2.318359  0.011274  0.822864

In [14]:
dframe2

Y         Q         X
0 -0.223685  1.763775 -2.205182
1  1.717797 -0.107035  1.239648
2  0.247564  1.095331 -0.721692

In [15]:
pd.concat([dframe1, dframe2])

X         Y         Z         Q
0 -0.189184  0.119048 -0.959709       NaN
1 -1.117993 -0.039461  0.286240       NaN
2  0.759573  0.736577 -0.124798       NaN
3  2.318359  0.011274  0.822864       NaN
0 -2.205182 -0.223685       NaN  1.763775
1  1.239648  1.717797       NaN -0.107035
2 -0.721692  0.247564       NaN  1.095331

In [17]:
pd.concat([dframe1, dframe2], ignore_index = True)

X         Y         Z         Q
0 -0.189184  0.119048 -0.959709       NaN
1 -1.117993 -0.039461  0.286240       NaN
2  0.759573  0.736577 -0.124798       NaN
3  2.318359  0.011274  0.822864       NaN
4 -2.205182 -0.223685       NaN  1.763775
5  1.239648  1.717797       NaN -0.107035
6 -0.721692  0.247564       NaN  1.095331