In [16]:
import numpy as np


In [3]:
arr = np.arange(50).reshape([10,5])

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [7]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [9]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [11]:
arr3d = np.arange(50).reshape([5, 5, 2])
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [20]:
arr3d = np.arange(200).reshape([10, 10, 2])
arr3d

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9],
        [ 10,  11],
        [ 12,  13],
        [ 14,  15],
        [ 16,  17],
        [ 18,  19]],

       [[ 20,  21],
        [ 22,  23],
        [ 24,  25],
        [ 26,  27],
        [ 28,  29],
        [ 30,  31],
        [ 32,  33],
        [ 34,  35],
        [ 36,  37],
        [ 38,  39]],

       [[ 40,  41],
        [ 42,  43],
        [ 44,  45],
        [ 46,  47],
        [ 48,  49],
        [ 50,  51],
        [ 52,  53],
        [ 54,  55],
        [ 56,  57],
        [ 58,  59]],

       [[ 60,  61],
        [ 62,  63],
        [ 64,  65],
        [ 66,  67],
        [ 68,  69],
        [ 70,  71],
        [ 72,  73],
        [ 74,  75],
        [ 76,  77],
        [ 78,  79]],

       [[ 80,  81],
        [ 82,  83],
        [ 84,  85],
        [ 86,  87],
        [ 88,  89],
        [ 90,  91],
        [ 92,  93],
        [ 94,  95],
        [ 96,  97],
        [ 98

In [30]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [32]:
arr.swapaxes(0,1)

AxisError: axis2: axis 1 is out of bounds for array of dimension 1