In [4]:
import numpy as np
arr = np.arange(5)

In [6]:
arr

array([0, 1, 2, 3, 4])

In [8]:
np.save("myarray",arr)

In [10]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.load("myarray.npy")

array([0, 1, 2, 3, 4])

In [16]:
arr1 = np.load("myarray.npy")
arr1

array([0, 1, 2, 3, 4])

In [18]:
arr2 = arr

In [20]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.savez("ziparray.npz",x= arr1,y = arr2)

In [24]:
archive_array = np.load("ziparray.npz")

In [26]:
archive_array["x"]

array([0, 1, 2, 3, 4])

In [28]:
archive_array["y"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.savetxt("mytextarray.txt",arr,delimiter=",")

In [38]:
arr = np.loadtxt("mytextarray.txt",delimiter=",")
arr

array([[1., 2., 3.],
       [4., 5., 6.]])