In [1]:
import numpy as np

In [3]:
my_list1 = [1,2,3,4]

In [7]:
my_array1 = np.array(my_list1)

In [9]:
my_array1

array([1, 2, 3, 4])

In [11]:
my_list2 = [11,22,33,44]

In [13]:
my_lists = [my_list1, my_list2]

In [17]:
my_array2 = np.array(my_lists)

In [21]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [23]:
my_array2.shape

(2, 4)

In [25]:
my_array2.dtype

dtype('int32')

In [27]:
 np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
my_zeros_array = np.zeros(5)


In [31]:
my_zeros_array.dtype


dtype('float64')

In [35]:
 np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [45]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])